[project]
name = "reading-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymupdf4llm>=0.2.9",
    "pypdf>=6.6.2",
    "rich>=14.3.1",
    "typer>=0.21.1",
]
